### ISSUE TITLE
volume in [of.movie]

### ISSUE THREAD

**Issue by H-MLim** [60-hz/Ofelia-Fast-Prototyping#4]
hello. can `[of.movie]` make sound of the video as well? I read the help file of it, but I'm afraid that I couldn't understand about the role of [volume $1(

**Comment by 60-hz** [comment]
Yes, the sound from the movie should come straight to your soundcard and speakers (or maybe the sound mixer under Windows...).

**Comment by H-MLim** [comment]
actually I think I figured out what's problem. maybe it depends on sound driver. (no sounds in ASIO driver but OK with MMIO). but if it's because the sound is from only my direct soundcard, I understand the limitation.

**Comment by H-MLim** [comment]
oh I found that this is not a problem of ASIO itself, but rather a problem of sound driver's compatibility with my computer system. since I checked that other interfaces with ASIO worked well, no worries for now. sorry for inconveniences.
