### ISSUE TITLE
menubar of [of.window]

### ISSUE THREAD

**Issue by H-MLim** [60-hz/Ofelia-Fast-Prototyping#5]
hello. are there any ways to disappear the menubar of` [of.window],` like `[border 0]` from `[gemwin]`?

**Comment by 60-hz** [comment]
The message [Fullscreen 1( should remove any menubar (at least it does on Apple computer).

**Comment by H-MLim** [comment]
it worked. will close this issue but since it seems the problem of windows when using `fullscreen` ( #3 ), will keep follow this.
